version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      # Add any installation commands here
  pre_build:
    commands:
      - echo "Executing pre-build commands..."
      # Add any pre-build commands here
  build:
    commands:
      - echo "Building the project..."
      # Add any build commands here
  post_build:
    commands:
      - echo "Executing post-build commands..."
      # Add any post-build commands here

artifacts:
  files:
    - '**/*'
  name: MyProject
